### PR TITLE
Change wording and remove stats

### PR DESCRIPTION
**Pull request by kevin-wangg**
Screenshot from 2021-04-14 21-34-58

### CODE REVIEW

**Comment by bonnie-chin** [comment]
Heyy just wanted to check two things
- is the big bold text 36px and the subtext 20px? the subtext just seems a lil small
- is there a way for us to make sure there's more than one word on the second line? (we could honestly just make the width of that smaller too ig LOL)

**Comment by kevin-wangg** [comment]
@bonnie-chin ya the big font is 36px and the smaller one is 20px

**Comment by judyzhong27** [comment]
The font looks a bit too bold, it should just be Bold not Extra Bold or Black.

The design has "arrange a donation" on the second line - I'm not sure I like how it looks with just one word on the second line. Any way to change this?

**Review by meganniu — APPROVED** [review]
code changes look good! thnx @kevinwang2040 
just merge whenever design says it's good

**Review by AinleyP — APPROVED** [review]
LGTM THANKS KEVIN !!

**Pull request merged**
