### PR TITLE
Secret manager setup

### LINKED ISSUE #6: Set up secret-manager
### Background
`secret-manager` stores project secrets (e.g. database passwords) in UWBlueprint's Hashcorp Vault. Github users that are part of UWBlueprint's Github org can authenticate and retrieve projects secrets through CLI.
`secret-manager` was developed by UWBlueprint's internal-tools team.

### Tasks
+ [ ] Set up `secret-manager` for `/client` and `/server`. 
  + [Set up instructions](https://www.notion.so/uwblueprintexecs/Secret-Management-2d5b59ef0987415e93ec951ce05bf03e)
+ [ ] Send Sherry Li your feedback about `secret-manager` set up 
+ [ ] Add a page in [our Notion](https://www.notion.so/uwblueprintexecs/Engineering-d4b263ea954f45708ff5a7c77c51b2cd) with helpful links/examples about using `secret-manager`
+ [ ] Do a demo of how to use `secret-manager` during weekly work session/standup

### PR DESCRIPTION
**Pull request by jlight99**
Closes #6

- Add config helper files from https://github.com/uwblueprint/vault-resources
- Add sample .env file

Note: our team vault path is "kv/pregnancy-centre"

Relevant setup guide: https://www.notion.so/uwblueprintexecs/Secret-Management-2d5b59ef0987415e93ec951ce05bf03e#3008f54889ab4b0cacfa276cbc43e613

### CODE REVIEW

**Review by sherryhli — COMMENTED** [review]
Setup looks good! Let me know if the auth issue was resolved.

Please also update the setup script with the [latest](https://github.com/uwblueprint/vault-resources/blob/master/update_secrets/setup.sh) from `vault-resources`, we fixed a mac compatibility issue (side note: is there a way to sync up files across different repos?)

**Comment by jlight99** [comment]
> Setup looks good! Let me know if the auth issue was resolved.
> 
> Please also update the setup script with the [latest](https://github.com/uwblueprint/vault-resources/blob/master/update_secrets/setup.sh) from `vault-resources`, we fixed a mac compatibility issue (side note: is there a way to sync up files across different repos?)

Thanks! Can confirm that auth issue was resolved.
As for syncing up files across repos, I did a bit of googling, and it looks like we'd have to write our own post-commit hook: https://stackoverflow.com/questions/19198787/how-to-conveniently-sync-a-file-between-two-git-repositories.

**Review by meganniu — APPROVED** [review]
LGTM! Thanks for setting this all up 

Could you add a section in the README which
- links the notion docs for secret manager
- tells people that they can pull secrets by running `vault kv get -format=json kv/pregnancy-centre | python3 update_secret_files.py`

I added the `.env` files to Vault, so try to pull and lmk how it goes :)

Also, dw about the failing CircleCI build.

**Comment by meganniu** [comment]
@sherryhli A possible solution for syncing files is [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Not sure about the nuances of using it, but maybe it could be helpful!

**Comment by sherryhli** [comment]
Cool, thanks for the suggestions! git submodules seem promising

**Review by chamod-gamage — APPROVED** [review]
Was able to successfully follow instructions on Notion and generate a .env file with the value for the key `REACT_APP_GRAPHQL_SERVER_URL`!
With the following CLI: `vault kv get -format=json kv/pregnancy-centre | python update_secret_files.py`
Couple things that we may want to include in the README:
- I had to use `python` instead of `python3` (this will depend on the user/OS)
- For Windows 10 users, make sure to run cmd/powershell as admin

**Comment by meganniu** [comment]
Could we also add a note to the README about how to update the `.env` files?
We should run the following command in the root
```vault kv put kv/pregnancy-centre CLIENT_ENV_VARS=@client/.env SERVER_ENV_VARS=@server/.env```

**Pull request merged**
