### PR TITLE
creating react and typescript project with eslint

### LINKED ISSUE #1: Set up web client
Submit a separate PR for every task :) It'll be easier to review.

Tasks
+ Under the folder `client/` in the root of this repo:
  + Create a react app that compiles Typescript. 
  + Add tslint
  + Start [here](https://github.com/facebook/create-react-app/releases/tag/v2.1.0).
+ Set up redux state/action/reducer to enable a request query to GraphQL
  + This task is partially blocked by #2 which exposes the GraphQL endpoint
+ Explore options for organizing component styling and components. Present the explorations during a work session so the team can decide together how to organize files.
  + We will be using [bootstrap components](https://getbootstrap.com/2.3.2/components.html)

### PR DESCRIPTION
**Pull request by azissac**
- create-react-app for new React app
- added typescript
- added eslint

### CODE REVIEW

**Comment by guy-ro** [comment]
Hi Anand, could you please remove/clean-up all the files we won't be using and commit that to this branch?

**Review by guy-ro — COMMENTED** [review]
Hi Anand, could you please remove all files that we won't be using that come with the create-react-app?

Besides that, looks good

**Review by guy-ro — APPROVED** [review]
Looks good!

**Comment by chamod-gamage** [comment]
Everything looks good on my side!

**Review by chamod-gamage — APPROVED** [review]

**Pull request merged**
