### PR TITLE
Fix Donor Homepage Styling

### PR DESCRIPTION
**Pull request by meganniu**
Fix styling problems on donor homepage
Text
+ Increase body text of landing page to 20px from 16px
+ Change “Last updated” to “Last added” for individual request groups

Responsiveness
+ On 1440, the text should be aligned to the pregnancy centre logo
+ Stretch the text to be aligned with the TPC logo, but keep the padding between the image and the text

Button
+ Change black send an email to the green 004D57 from the admin login screens

Spacing
+ Can we get the padding between the right line of the list and the middle section to be equal to the padding between the middle section and the right side’s gray boxes always?
+ Padding at the top between the top line and the content (where Games starts) is too tight
+ The gray lines on each individual list item should always extend to 32 px from the right gray line of the list
+ Align banner text to the TPC logo
+ Banner text should only be 3 lines, not 4 at 1440

Interaction
+ Items in list should be clickable and have click cursor
+ Going to new pages in the scrolling list should bring the list back to start
+ Make sure cut off items in list don’t shift when clicked

Screenshot from 2021-04-04 22-22-13

https://user-images.githubusercontent.com/20423590/113530207-6f999780-9593-11eb-99af-0b73a1abfbf9.mov

### CODE REVIEW

**Review by kevin-wangg — APPROVED** [review]
lgtm!

**Comment by judyzhong27** [comment]
Question: since the video cut off, does the button return to the Send an email state after about 10 seconds? Or after they refresh the page?

UI Note: 
- Can the pagination arrows be a little bigger as in the spec? Just so I can distinguish between disabled/active.
- Sorry, the copied state of the send an email button and the hover state should have the text and outline this colour: 004D57. Figma was updated
- The subheading text underneath "Support..." is too tight. Should be at least +8px of the font size, so 24

Lastly, could we change the copy for the number to their actual number? It's (519) 886-4001.

Also, not sure if the tabs have been pushed yet but for now, we don't have How to Donate going anywhere, so could we hide that button?

Everything else looks gr8!

**Comment by meganniu** [comment]
@judyzhong27  Thanks for the review!!! PR description is updated with new images/video

> does the button return to the Send an email state after about 10 seconds? Or after they refresh the page?

Yup, send email button returns to original state after 10 seconds or on refresh. Fixed the video :))) sorry!

> Can the pagination arrows be a little bigger as in the spec? Just so I can distinguish between disabled/active.

Done ✔️

>  the copied state of the send an email button and the hover state should have the text and outline this colour: 004D57. Figma was updated

Done ✔️

> The subheading text underneath "Support..." is too tight. Should be at least +8px of the font size, so 24

Done ✔️

I ended up going with the spec on the figma for subheading text (20px font size, 28px line height). lmk if we need 24px font size instead.

> change the copy for the number to their actual number? It's (519) 886-4001.

Done ✔️

> we don't have How to Donate going anywhere, so could we hide that button?

Done ✔️

**Review by azissac — APPROVED** [review]
LGTM!!

**Review by Anand-Issac — APPROVED** [review]
LGTM

**Pull request merged**
