### PR TITLE
Fix spacing requestgroupdonorview

### PR DESCRIPTION
**Pull request by guy-ro**
- RequestGroupDonorView is now responsive (but not responsive in a nice way, should be discussed with designers how it should look on smaller screens eventually) using Bootstrap Row/Col (at least it doesn't break the entire display on smaller screens atm)
- RequestGoupDonorView is now not positioned by pixel location but by relative position in its Col in DonorRequestGroupBrowser
- Fixed issue where React Bootstrap was overwriting style for bottom border for last RequestTypeListItem
- Fixed some differences in spacing between footer and Figma
- Fixed spacing with "Open Requests" header

Normal desktop screen:
image

Narrow screen:
image

### CODE REVIEW

**Comment by guy-ro** [comment]
For fun, here's a before for normal screens:
image

and for narrow screens:
image

**Review by meganniu — APPROVED** [review]
Wow this looks amazing! thank you for paying attn to styling 🎨

I've pushed a commit for more styling (to make width of components dynamic). Feel free to revert changes if u don't like them


https://user-images.githubusercontent.com/20423590/111870847-5969c580-895d-11eb-9b5a-23fc023ca6ef.mov

**Review by kevin-wangg — APPROVED** [review]
lgtm!

**Comment by guy-ro** [comment]
I worked in your changes @meganniu and made a few more changes to make it fit a bit better with the Figma (e.g. using max-width). Take a look:

image

image

**Comment by guy-ro** [comment]
Fixed some resizing issues for footer mostly:

image
image
image
image
image

**Review by meganniu — APPROVED** [review]
LGTM!! thanks again :))))

**Pull request merged**
