### PR TITLE
Modal design updates

### PR DESCRIPTION
**Pull request by chamod-gamage**
Currently blocked by https://github.com/uwblueprint/pregnancy-centre/pull/101 
Addressed the following feedback from @bonnie-chin 
> - I think the modal header font size should be bigger? is it 24px?
> - left margin of the filler text in the sign in is a bit too big I think? It should be the same as the margin in "Modal Input Field Errors" 
> - are we doing the icon symbols :O ? I noticed that the alert icon wasn't there
> ^^ styling feedback is in order of priority

- Changed styling for title in CommonModal to 24px
- Slightly changed left margin of placeholders to 19px. Unfortunately, due to CSS limitations the placeholder and cursor can't have different margins so I just used the 19px margin over the 16px margin but the gap is much more reasonable now.
- Alert Icon symbols have been included on error except for the password input on signin because of the Eye icon already there

- Also removed Spacer component and replaced with margins per request from @meganniu 

Edit: Adding ss

Implementation
image
image

Design
image

### CODE REVIEW

**Comment by bonnie-chin** [comment]
:OO do you have screenshots 😅

**Comment by bonnie-chin** [comment]
Last few comments I promise LOL
- Can we make the button width match the input fields? I think there's a fixed width that you guys defined for the input fields but not the button from what I saw 
- No periods after the error text :D 
- Modals should have border-radius of 12px 

Awesome job tho wow guys 🤩🤩

**Comment by chamod-gamage** [comment]
Should be good now @bonnie-chin !
image

**Review by bonnie-chin — COMMENTED** [review]
:O wait can we get the button width to match the input field width
> Should be good now @bonnie-chin !
> image

**Comment by chamod-gamage** [comment]
image
lol i forgot to include the last commit

**Comment by bonnie-chin** [comment]
> lol i forgot to include the last commit

yup looks good to me I can't find the approval button but 👍👍

**Review by bonnie-chin — APPROVED** [review]

**Comment by meganniu** [comment]
#101 merged :)))) @chamod-gamage

**Review by meganniu — APPROVED** [review]
LGTM, thanks so much!!!!

**Pull request merged**
