### PR TITLE
fixed width issues with RequestTypeList

### PR DESCRIPTION
**Pull request by guy-ro**
Width of RequestTypeList table rows is now responsive to screen width.

Image with large screen followed by image with small screen.
image
image

### CODE REVIEW

**Comment by bonnie-chin** [comment]
lgtm!! dunno if there's any easy fix to having the "displaying X..." to extend further outwards but that's my only comment
a sidenote that's unrelated to this pull would be that the grey bars don't line up with the left edge of the header 😅

**Comment by guy-ro** [comment]
@bonnie-chin now looks like this on a large screen and very small screen:

image
image

**Review by kevin-wangg — APPROVED** [review]
LGTM!

**Review by meganniu — APPROVED** [review]
LGTM!

**Pull request merged**
