### PR TITLE
changed styling for hover on active button, fixed incorrect selectors

### PR DESCRIPTION
**Pull request by guy-ro**
Now looks like this (instead of being invisible) on hover:

image

### CODE REVIEW

**Review by meganniu — APPROVED** [review]
Code changes LGTM.
Although the size of the circle for the selected page changes on hover. 
@bonnie-chin @judyzhong27 Is that the behaviour you want?

**Comment by bonnie-chin** [comment]
> Code changes LGTM.
> Although the size of the circle for the selected page changes on hover.
> @bonnie-chin @judyzhong27 Is that the behaviour you want?

Yeahh if we can not change the size of the circle on hover I think that'd be good :D

**Comment by guy-ro** [comment]
Updated with larger circle on hover
image

**Review by bonnie-chin — APPROVED** [review]
design looks gouda

**Pull request merged**
